### ISSUE TITLE
Crash FTB Relevation

### ISSUE THREAD

**Issue by Andy2k** [JackyyTV/IntegrationForegoing#31]
Want add this Mod, but the Game Crash:
I use FTB Revelation without Gadgetry and Thaumcraft and with Mystical Agriculture.

I have no Idea, what I can do, so I hope it´s a Modproblem :D

----

Description: Initializing game

java.lang.NoClassDefFoundError: jackyy/integrationforegoing/integration/straw/StrawRegistryIE$1
	at jackyy.integrationforegoing.integration.straw.StrawRegistryIE.register(StrawRegistryIE.java:21)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1611_StrawRegistryIE_register_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:762)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:628)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:246)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: jackyy.integrationforegoing.integration.straw.StrawRegistryIE$1
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 17 more
Caused by: java.lang.NoClassDefFoundError: com/buuz135/industrial/utils/apihandlers/straw/StrawHandlerBase
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 19 more
Caused by: java.lang.ClassNotFoundException: com.buuz135.industrial.utils.apihandlers.straw.StrawHandlerBase
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 23 more

**Comment by JackyyTV** [comment]
From what I can see, looks like it's something to do with my Immersive Engineering straw drinking integration, I am not 100% sure what happened there, so further investigation is needed.

**Comment by ZXQWAS** [comment]
This limitation doesn't seem to be showing up properly, it still crashes. However when I do update Industrial Foregoing, there's no crash at startup  anymore.

**Comment by JackyyTV** [comment]
I am aware that it's an issue with the mod version, however, Industrial Foregoing has a very weird internal version naming scheme, so it seems like I can't limit the minimum required mod version properly regardless. The minimum version required for the addon to not crash is 1.10.6 or above.
