### ISSUE TITLE
release update crashing

### ISSUE THREAD

**Issue by phantom1151** [JackyyTV/IntegrationForegoing#36]
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Integration Foregoing (integrationforegoing)
Caused by: java.lang.NoSuchMethodError: com.buuz135.industrial.api.recipe.LaserDrillEntry.<init>(ILnet/minecraft/item/ItemStack;I)V
	at jackyy.integrationforegoing.util.ModUtils.addCustomLaserDrillEntryBlock(ModUtils.java:108)
	at jackyy.integrationforegoing.integration.laserdrill.LaserDrillHandlerMysticalAgriculture.init(LaserDrillHandlerMysticalAgriculture.java:9)
	at jackyy.integrationforegoing.integration.Integrations.init(Integrations.java:139)
	at jackyy.integrationforegoing.proxy.CommonProxy.init(CommonProxy.java:15)
	at jackyy.integrationforegoing.proxy.ClientProxy.init(ClientProxy.java:18)
	at jackyy.integrationforegoing.IntegrationForegoing.init(IntegrationForegoing.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:744)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Buuz135** [comment]
I thought I added enough precautions so stuff like this didn't happen, sorry! There isn't currenly a fix as I removed the ability of adding ores through code. Now they can only be added by json in the folder "config/laser_drill_ores"

**Comment by phantom1151** [comment]
ignore this i found that it was the new industrial foregoing update causing the crash but it could be a compatablitly with yours so might still want to look into it

**Comment by TheSnowyChickens** [comment]
Hi,
I have the same crash. (after IF update)

**Comment by JackyyTV** [comment]
I'll push a hotfix to temporarily fix this for now, the Laser Drill compat will be completely disabled until I can work out a way to generate the JSON files needed for the compat.

**Comment by JackyyTV** [comment]
Fixed in [1.8.1](https://minecraft.curseforge.com/projects/integration-foregoing/files/2651232) for now.
